### ISSUE TITLE
Color loss - unlearning superpixels

### ISSUE THREAD

**Issue by Goldyy** [fuy34/superpixel_fcn#26]
Hello Fengting,

First of all I want to say thank you for for your work and the provided code. Working with it is great but I have the following issue: I'm trying to jointly learn superpixels and an optical flow net.
I use the sintel dataset, cielab color features and the color loss like you did in the stereo application https://github.com/fuy34/superpixel_fcn/issues/12#issuecomment-823740528. The problem I have is that I do not learn super pixels. To further narrow down the problem I freeze the optical flow net and start with the provided model (pretrained on the segmentation task). After a few iterations (around 300) I have unlearned the superpixels (they are squares). I experimented with the pos weight parameter but it does not have an effect on the superpixels.

Do you have any idea what the problem is?

**Comment by fuy34** [comment]
Without diving deep into your implementation and experiment log, it is hard to tell the exact reason. 

Does the color losses, especially its data term, decrease? If not, it may be an implementation issue. 
Otherwise, try to set the pos_weight as 0. This will totally remove the regularization. If the implementation is correct, and the color loss drops, it should get some sort of superpixels. 
Also, my current implementation only supports the image whose ```img_h ```and ```img_w``` is dividable by ```downsize``` (issue #19)

Sintel is a synthetic dataset, I would imagine it performs somewhat similar to the HR-VS result shown on the paper. But if you wish to switch to a real-world dataset (e.g. Kitti) later, additional pre-processing may be needed https://github.com/fuy34/superpixel_fcn/issues/10#issuecomment-803210807.

**Comment by Goldyy** [comment]
Thank you for the quick reply! I was able to find my mistake.
