### ISSUE TITLE
Can the given model generate superpixels of given number?

### ISSUE THREAD

**Issue by lisiyaoATbnu** [fuy34/superpixel_fcn#3]
Hi all，
你们的工作非常有趣！
但是请问这个模型可以生成指定数量的superpixel吗？还是只能生成固定数量的呢？
多谢多谢！

**Comment by fuy34** [comment]
Hi, 
Thanks for your interest in our work. For the convenience of other non-Chinese speakers, I will answer the question in English. 

A short answer is Yes. However, as we descript in the paper, we need to resize the input image to achieve so. We do not have a hyperparameter to control the superpixel number. Instead, we define the grid size for each pixel. 

The default setting is to get 16*16 grid size superpixel, then with input size 320*480, the model will get around 600 superpixels. But please note, the number will not be exactly the same, because of the connection operation.  Then if we want 2400 superpixels (8*8 grid size), for example, we need to resize the input image to 640*960. The model will still generates 16*16 superpixels first, and then we can resize the output back to 320*480. The result would be the same as getting 8*8 grid size superpixels. 

Please refer to our run_infer_nyu.py code for the details of implementation. You may want to start at line 125 to understand how the resizing works. Thanks

**Comment by liuxy1103** [comment]
I wonder if i can achieve it by training a new model with different downsample size hyper-parameter
