### ISSUE TITLE
About PSMNet

### ISSUE THREAD

**Issue by honeyhoney979** [fuy34/superpixel_fcn#6]
Dear authors,
The paper and the code are impressive. Specially, I am very impressive about the idea that modify PSMNet for stereo matching to simultaneously predict superpixels and disparities. But saddly, I can't find the code about the PSMNet. And I can't see the effect of stereo Matching which benifit form superpixel. If you have time, would you mind answer my question.

Thanks!

**Comment by fuy34** [comment]
Hi, 

Thank you for your interest in our work. 

We do not have a recent plan to release the code for this part, because the way to build SPPSMNet is very intuitive. We just need to stack our SpixelNet and PSMNet together.  And after the data loader, we can simply use SpixelNet to process the image, and then put that into PSMNet. The only modifications we need for PSMNet are: (1) to remove all the stride-2 convolution to stride 1, and (2) up-sample the output cost volume with feature function in our repo. These details are described in our supplement material.

**Comment by mszuyx** [comment]
@fuy34 First of all, fantastic work!

Our team is trying to merge SpixelNet with our task network as well to improve the segmentation boundary accuracy. We do believe this will greatly push the performance of the task network further! However, as we followed your supplement material, we have some confusions:
![Screenshot 2021-12-15 15:22:48](https://user-images.githubusercontent.com/37651144/146269518-eb7d47f3-af60-46c7-a214-1842a8a63c04.png)

1. There is a layer called "**sImg_1/2**" using the kernel named "**assoc_1/2**" and stride 4 to down sample the association map that output by SpixelNet (the H x W x 9 tensor) to (1/4 H x 1/4 W x 3). This of course makes sense since most of the backbone / task network only take 3 channel input (RGB images). So in order to merge the two model, we need to massage the output of SpixelNet to some 3 channel tensors. So, if I understand this correctly, this "**sImg_1/2**" is a custom conv2d layer that doesn't belong to SpixelNet nor PSMNet? If so, does it require any special initialization / activation? (Also I'm guessing the "1/2" denotes left/right image?)
2. Furthermore, when you mentioned in the paper: "_replace the conventional operations for downsampling (e.g., stride-2 convolutions) and upsampling (e.g., bilinear upsampling) in the task network with a superpixel-based ownsampling/upsampling scheme to effectively preserve object boundaries and fine details._" What operations did you use for the "upsampling"? Judging by the supplement material, it seems like a concatenation between the upsampled output from the PSMNet and the association map "**assoc_1**" (the H x W x 9 tensor? Yet it is marked H x W x D) along dimension one, and maybe followed by some conv2d to make sure the tensor shape satisfies the input shape of the disparity regression module? And why the "**assoc_1**" has stride 4?

It will be really helpful if we can get some input from you directly! Thanks! :  )
