### ISSUE TITLE
Results of other methods

### ISSUE THREAD

**Issue by moothes** [fuy34/superpixel_fcn#7]
Hi, thanks for your great work and public code.
Can you provide all the results.csv files of other methods so I can draw the curves as in your paper?

Thanks!

**Comment by fuy34** [comment]
I am sorry. I was trying to find the results, but I guess I may have deleted them due to the disk space.
I only have the seal's result on BSDS500 benchmark saved on my local computer. I can email you if needed. 
It should not be too hard to reproduce the result by running the code from the original authors and [this benchmark](https://github.com/davidstutz/superpixel-benchmark).

**Comment by moothes** [comment]
Thanks for your reply!  I will try to reproduce these methods.
My email address is zhouhj26@mail2.sysu.edu.cn.
By the way, I'm new to this task and somehow curious about the ground truth labels. What is the meaning about their annotations?
